//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Square_Grocery_StoreEntities : DbContext
    {
        public Square_Grocery_StoreEntities()
            : base("name=Square_Grocery_StoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catagory> Catagories { get; set; }
        public virtual DbSet<CatUserRole> CatUserRoles { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderMain> OrderMains { get; set; }
        public virtual DbSet<OrderProgress> OrderProgresses { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    
        public virtual ObjectResult<GetAllOrder_Result> GetAllOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrder_Result>("GetAllOrder");
        }
    
        public virtual ObjectResult<GetOrderDetailByCustomer_Result> GetOrderDetailByCustomer(Nullable<long> customerInfoId)
        {
            var customerInfoIdParameter = customerInfoId.HasValue ?
                new ObjectParameter("CustomerInfoId", customerInfoId) :
                new ObjectParameter("CustomerInfoId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderDetailByCustomer_Result>("GetOrderDetailByCustomer", customerInfoIdParameter);
        }
    
        public virtual ObjectResult<GetOrderTrackingRecord_Result> GetOrderTrackingRecord(string trackingNo)
        {
            var trackingNoParameter = trackingNo != null ?
                new ObjectParameter("TrackingNo", trackingNo) :
                new ObjectParameter("TrackingNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderTrackingRecord_Result>("GetOrderTrackingRecord", trackingNoParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> SaveCustomerOrder(string name, string phone, string email, Nullable<decimal> totalAmount, string address, Nullable<byte> orderStatus, string trackingNumber, string products)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var totalAmountParameter = totalAmount.HasValue ?
                new ObjectParameter("TotalAmount", totalAmount) :
                new ObjectParameter("TotalAmount", typeof(decimal));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var orderStatusParameter = orderStatus.HasValue ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(byte));
    
            var trackingNumberParameter = trackingNumber != null ?
                new ObjectParameter("TrackingNumber", trackingNumber) :
                new ObjectParameter("TrackingNumber", typeof(string));
    
            var productsParameter = products != null ?
                new ObjectParameter("Products", products) :
                new ObjectParameter("Products", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("SaveCustomerOrder", nameParameter, phoneParameter, emailParameter, totalAmountParameter, addressParameter, orderStatusParameter, trackingNumberParameter, productsParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SaveNewUser(string fullName, string email, string password, string phone, Nullable<System.DateTime> createdDate)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("CreatedDate", createdDate) :
                new ObjectParameter("CreatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SaveNewUser", fullNameParameter, emailParameter, passwordParameter, phoneParameter, createdDateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SaveOrderStatus(Nullable<long> orderMainId, Nullable<System.DateTime> orderDate, Nullable<System.DateTime> orderTime, Nullable<byte> status, string comments)
        {
            var orderMainIdParameter = orderMainId.HasValue ?
                new ObjectParameter("OrderMainId", orderMainId) :
                new ObjectParameter("OrderMainId", typeof(long));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var orderTimeParameter = orderTime.HasValue ?
                new ObjectParameter("OrderTime", orderTime) :
                new ObjectParameter("OrderTime", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SaveOrderStatus", orderMainIdParameter, orderDateParameter, orderTimeParameter, statusParameter, commentsParameter);
        }
    
        public virtual ObjectResult<UM_AuthenticateUser_Result> UM_AuthenticateUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UM_AuthenticateUser_Result>("UM_AuthenticateUser", usernameParameter, passwordParameter);
        }
    }
}
